#!/usr/bin/env python3
"""Synchronize project documentation into the website repository."""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


SENSITIVE = (re.compile(r"^\.env(?:\..*)?$", re.I), re.compile(r"^\.mise\.local\.toml$", re.I), re.compile(r"\.(?:p12|jks|pem|key)$", re.I), re.compile(r"(?:secret|token|password)", re.I))
WIKILINK = re.compile(r"\[\[(?P<target>[^\]|#]+)(?:#(?P<anchor>[^\]|]+))?(?:\|(?P<label>[^\]]+))?\]\]")


def full(path: str | Path) -> Path:
    return Path(path).expanduser().resolve()


def contained(root: Path, relative: str, description: str) -> Path:
    root = full(root)
    candidate = (root / relative.replace("/", "/")).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as exc:
        raise RuntimeError(f"{description} path escapes its root: {relative}") from exc
    return candidate


def relative(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def sensitive_path(path: str) -> bool:
    return any(pattern.search(Path(path).name) or pattern.search(path) for pattern in SENSITIVE)


def title(content: str, fallback: str) -> str:
    match = re.search(r"^#\s+(.+?)\s*$", content, re.MULTILINE)
    return match.group(1).strip() if match else fallback


def yaml_single(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def frontmatter(content: str, page_title: str) -> str:
    normalized = content.lstrip("\r\n")
    match = re.match(r"\A---\r?\n(?P<body>.*?)\r?\n---\r?\n?", normalized, re.S)
    if match:
        body = match.group("body").rstrip()
        if not re.search(r"^layout\s*:", body, re.MULTILINE):
            body = "layout: doc\n" + body
        if not re.search(r"^title\s*:", body, re.MULTILINE):
            body = f"title: {yaml_single(page_title)}\n" + body
        rest = normalized[match.end() :].lstrip("\r\n").rstrip()
        return f"---\n{body}\n---\n\n{rest}\n"
    return f"---\nlayout: doc\ntitle: {yaml_single(page_title)}\n---\n\n{normalized.rstrip()}\n"


def strip_md(path: str) -> str:
    path = path.replace("\\", "/")
    return path[:-3] if path.lower().endswith(".md") else path


def normalize_key(key: str) -> str:
    return key.strip().replace("\\", "/").lstrip("./").rstrip("/")


def route(section: str, target: str) -> str:
    no_ext = strip_md(target)
    return f"/{section}/" if no_ext == "index" else f"/{section}/{no_ext}"


def group_title(source: str) -> str:
    parent = Path(source).parent.name
    return "项目总览" if not parent or parent == "." else re.sub(r"^\d+[-_]", "", parent)


def mts(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'").replace("\r", "").replace("\n", "\\n") + "'"


def sidebar(pages: list[dict], path: Path) -> None:
    groups: dict[str, list[dict]] = {}
    for page in sorted((item for item in pages if item["section"] == "spectra-admin"), key=lambda item: item["source"]):
        groups.setdefault(page["group"], []).append(page)
    blocks: list[str] = []
    for name, items in groups.items():
        entries = ",\n".join(f"        {{ text: {mts(item['title'])}, link: {mts(item['route'])} }}" for item in items)
        blocks.append(f"    {{\n        text: {mts(name)},\n        items: [\n{entries}\n        ]\n    }}")
    designers = sorted((item for item in pages if item["section"] == "logicflow-flowable"), key=lambda item: item["source"])
    designer_sidebar = "[]" if not designers else f"[\n    {{ text: {mts(designers[0]['title'])}, link: {mts(designers[0]['route'])} }}\n]"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("// Generated by scripts/sync-website-docs.sh. Do not edit manually.\n"
                    "export const projectSidebar = [\n" + ",\n".join(blocks) +
                    f"\n]\n\nexport const designerSidebar = {designer_sidebar}\n", encoding="utf-8")


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def git_changes(website: Path, roots: list[str]) -> list[str]:
    if not (website / ".git").exists():
        return []
    command = ["git", "-c", f"safe.directory={website}", "-C", str(website), "status", "--short", "--", *roots]
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError("无法读取 website 仓库状态。")
    return [line for line in result.stdout.splitlines() if line.strip()]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", default=None)
    parser.add_argument("--website-root", required=True)
    parser.add_argument("--mode", choices=("Preview", "Apply"), default="Preview")
    parser.add_argument("--prune-legacy", action="store_true")
    parser.add_argument("--allow-dirty-project-docs", action="store_true")
    parser.add_argument("--build", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.build and args.mode != "Apply":
        raise RuntimeError("--build 只能与 --mode Apply 一起使用。")
    source_root = full(args.source_root or Path(__file__).parent.parent)
    website_root = full(args.website_root)
    manifest_path = source_root / "scripts/website-docs-manifest.json"
    if not source_root.is_dir():
        raise RuntimeError(f"源仓库目录不存在: {source_root}")
    if not website_root.is_dir():
        raise RuntimeError(f"网站仓库目录不存在: {website_root}")
    if not manifest_path.is_file():
        raise RuntimeError(f"发布清单不存在: {manifest_path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("version") != 1:
        raise RuntimeError(f"不支持的发布清单版本: {manifest.get('version')}")

    source_docs = contained(source_root, manifest["source"]["docsRoot"], "源文档")
    website_docs = contained(website_root, "docs", "网站文档")
    blog_root = contained(website_root, "docs/pages/blogs", "博客")
    if not blog_root.is_dir():
        raise RuntimeError(f"网站博客目录不存在: {blog_root}")
    if not (website_root / "package.json").is_file():
        raise RuntimeError(f"网站 package.json 不存在: {website_root}")
    targets = manifest["targets"]
    spectra_target = contained(website_root, targets["spectra"], "Spectra 生成目录")
    designer_target = contained(website_root, targets["designer"], "流程设计器生成目录")
    assets_target = contained(website_root, targets["assets"], "附件生成目录")
    sidebar_relative = targets["generatedSidebar"]
    generated_manifest_relative = targets["generatedManifest"]
    sidebar_path = contained(website_root, sidebar_relative, "侧边栏生成文件")
    generated_manifest_path = contained(website_root, generated_manifest_relative, "同步清单生成文件")
    managed_roots = sorted({targets["spectra"], targets["designer"], targets["assets"], Path(sidebar_relative).parent.as_posix()})
    dirty = git_changes(website_root, managed_roots)
    if dirty and not args.allow_dirty_project_docs:
        raise RuntimeError("website 项目文档生成区存在未提交修改，请先处理:\n" + "\n".join(dirty))
    if dirty:
        print("警告: 已允许覆盖 website 项目文档生成区中的未提交修改。", file=sys.stderr)

    route_map: dict[str, str | None] = {}
    basename_routes: dict[str, set[str]] = {}
    source_files: list[str] = []
    pages: list[dict] = []
    excluded = manifest["source"].get("excludeGlobs", [])
    designer_sources = set(manifest.get("designerSources", []))
    overrides = manifest.get("routeOverrides", {})

    def add_route(key: str, value: str) -> None:
        key = normalize_key(key)
        if not key:
            return
        if key in route_map and route_map[key] != value:
            route_map[key] = None
        else:
            route_map[key] = value

    for file in sorted(source_docs.rglob("*.md")):
        source_relative = relative(source_docs, file)
        if sensitive_path(source_relative) or any(fnmatch.fnmatchcase(source_relative, pattern) for pattern in excluded):
            continue
        source_files.append(source_relative)
        is_designer = source_relative in designer_sources
        section = "logicflow-flowable" if is_designer else "spectra-admin"
        target_relative = str(overrides.get(source_relative, "index.md" if is_designer else source_relative))
        if not target_relative.lower().endswith(".md"):
            target_relative += ".md"
        target_root = designer_target if is_designer else spectra_target
        target_path = contained(target_root, target_relative, "文档目标")
        item = {
            "source": source_relative,
            "target": relative(website_root, target_path),
            "path": file,
            "section": section,
            "route": route(section, target_relative),
            "group": "流程设计器" if is_designer else group_title(source_relative),
            "title": title(file.read_text(encoding="utf-8"), file.stem),
        }
        pages.append(item)
        add_route(source_relative, item["route"])
        add_route(strip_md(source_relative), item["route"])
        basename_routes.setdefault(file.stem, set()).add(item["route"])
    for name, routes in basename_routes.items():
        if len(routes) == 1:
            add_route(name, next(iter(routes)))

    warnings: list[str] = []
    generated_files: set[str] = set()
    with tempfile.TemporaryDirectory(prefix="spectra-docs-sync-") as temp:
        temp_root = Path(temp)
        stage = temp_root / "stage"
        backup = temp_root / "backup"
        for page in pages:
            content = page["path"].read_text(encoding="utf-8")

            def convert(match: re.Match[str]) -> str:
                target = normalize_key(match.group("target"))
                no_ext = strip_md(target).rstrip("/")
                resolved = route_map.get(target) or route_map.get(no_ext)
                if not resolved:
                    warnings.append(f"无法解析内部链接 [{page['source']}]: {target}")
                    return match.group(0)
                anchor = f"#{match.group('anchor').strip()}" if match.group("anchor") else ""
                label = match.group("label") if match.group("label") else target
                return f"[{label}]({resolved}{anchor})"

            content = WIKILINK.sub(convert, content)
            output = frontmatter(content, page["title"])
            staged = stage / page["target"]
            staged.parent.mkdir(parents=True, exist_ok=True)
            staged.write_text(output, encoding="utf-8")
            generated_files.add(page["target"])

        for attachment in manifest.get("attachments", []):
            source_relative = str(attachment["source"])
            if sensitive_path(source_relative):
                raise RuntimeError(f"附件命中敏感文件规则: {source_relative}")
            source_path = contained(source_docs, source_relative, "附件源文件")
            if not source_path.is_file():
                warnings.append(f"附件源文件不存在: {source_relative}")
                continue
            target_path = contained(assets_target, str(attachment["target"]), "附件目标")
            target_relative = relative(website_root, target_path)
            staged = stage / target_relative
            staged.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source_path, staged)
            generated_files.add(target_relative)

        staged_sidebar = stage / sidebar_relative
        sidebar(pages, staged_sidebar)
        generated_files.add(sidebar_relative)
        generated_files.add(generated_manifest_relative)
        generated_manifest = {"version": 1, "files": sorted(generated_files), "sources": sorted(source_files)}
        staged_manifest = stage / generated_manifest_relative
        staged_manifest.parent.mkdir(parents=True, exist_ok=True)
        staged_manifest.write_text(json.dumps(generated_manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

        previous = None
        if generated_manifest_path.is_file():
            try:
                previous = json.loads(generated_manifest_path.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                warnings.append("无法读取旧同步清单，将跳过常规过期文件清理。")
        stale: set[str] = set()
        if args.prune_legacy:
            for root in (spectra_target, designer_target, assets_target):
                if root.is_dir():
                    for path in root.rglob("*"):
                        if path.is_file():
                            rel = relative(website_root, path)
                            if not rel.lower().startswith("docs/pages/blogs/"):
                                stale.add(rel)
        elif previous:
            stale.update(str(item) for item in previous.get("files", []) if str(item) not in generated_files)
        stale.difference_update(generated_files)
        planned_adds = sorted(item for item in generated_files if not (website_root / item).is_file())
        planned_changes = sorted(item for item in generated_files if (website_root / item).is_file() and digest(stage / item) != digest(website_root / item))
        planned_deletes = sorted(item for item in stale if (website_root / item).is_file())
        if any(item.lower().startswith("docs/pages/blogs/") for item in planned_deletes):
            raise RuntimeError("删除计划意外包含 blogs 文件。")
        print(f"文档同步模式: {args.mode}")
        print(f"源文档: {len(source_files)} 个 Markdown，{len(pages)} 个页面")
        print(f"新增: {len(planned_adds)}")
        for item in planned_adds:
            print(f"  + {item}")
        print(f"修改: {len(planned_changes)}")
        for item in planned_changes:
            print(f"  ~ {item}")
        print(f"删除: {len(planned_deletes)}")
        for item in planned_deletes:
            print(f"  - {item}")
        for warning in warnings:
            print(f"警告: {warning}", file=sys.stderr)
        if args.mode == "Preview":
            print("Preview 完成，未修改 website。")
            return 0

        backup.mkdir(parents=True, exist_ok=True)
        for root in managed_roots:
            actual = contained(website_root, root, "受控生成目录")
            if actual.exists():
                saved = backup / root
                saved.parent.mkdir(parents=True, exist_ok=True)
                if actual.is_dir():
                    shutil.copytree(actual, saved)
                else:
                    shutil.copy2(actual, saved)
        try:
            for item in planned_deletes:
                (website_root / item).unlink(missing_ok=True)
            for item in sorted(generated_files):
                target = website_root / item
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(stage / item, target)
            if args.build:
                subprocess.run(["pnpm", "run", "docs:build"], cwd=website_root, check=True)
        except Exception:
            for root in managed_roots:
                actual = contained(website_root, root, "回滚目录")
                if actual.exists():
                    shutil.rmtree(actual) if actual.is_dir() else actual.unlink()
                saved = backup / root
                if saved.exists():
                    actual.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copytree(saved, actual) if saved.is_dir() else shutil.copy2(saved, actual)
            raise
        print("Apply 完成。脚本未执行 Git commit 或 push。")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (RuntimeError, OSError, json.JSONDecodeError, subprocess.CalledProcessError) as exc:
        print(f"错误: {exc}", file=sys.stderr)
        raise SystemExit(1)
